version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cineminha_tropa
    ports:
      - "3009:3009"
    environment:
      TZ: America/Sao_Paulo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

